### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [pablo-invernon/API-RESTful#5]
Hi,<br><br>url : https://github.com/pablo-invernon/API-RESTful/blob/91b78e14efb64586122955a2f23f06379e046605/docker/credentials <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by pablo-invernon** [comment]
Oh my god!

I never had used github. I always had been working with private repositories.

Thank you very much!!!!

Could I delete this history entry?

**Comment by shaybenb** [comment]
yes you can , google it :)

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
